---
title: "lab3_assembly_annotation.Rmd"
output: html_document
date: "2025-09-25"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
```{r libraries}
library('Biostrings')
library("IRanges")
library("GenomicRanges")
library("Rsamtools")
library("GenomicAlignments")
library("Gviz")
```


## Question 1

```{r q1, eval = FALSE}
	Total length:	12672120
	Fragments:	354
	Fragments N50:	52932
	Largest frg:	302365
	Scaffolds:	0
	Mean coverage:	8
 make this into table
```

##Question 2
complete: 1110
single copy complete: 1106
duplicated complete: 4
fragmented: 13
missing: 3282
low coverage so low busco expected
N50: 52 kbp (same as flye, but less precise)
total assembly length: 12672120
```{r q2}

```

##Question 3
genome fraction: 0.528, busco was closer to 1/3
duplication ratio: 1.156 
0 misassemblies

##Question 4

```{r q4}
Scerevisiae <- readDNAStringSet('/Users/mtaillefer00/Documents/BIOL_4315_LAB_3_MT/data/GCF_000146045.2_R64_genomic.fna')
names(Scerevisiae)
writeXStringSet(Scerevisiae[1],'data/R64_chr1.fna')
```

##Question 5

```{r q5, fig.width=16, fig.height=12}

library(GenomicRanges)

######## 1. Import the Bam file and convert it into a Granges object #########

#BAM file path
bam_file<- '/Users/mtaillefer00/Documents/BIOL_4315_LAB_3_MT/data/contig_vs_chr1.sorted.bam'

# Open connection to bam file
bam <- BamFile(bam_file)

#Read all alignments (already restricted to chr1)
alns <- readGAlignments(bam)

# Convert to GRanges object
gr_alns <- granges(alns)

####### 2. Create 'Tracks' showing the alignment ############
options(ucscChromosomeNames=FALSE)
aln_track <- AnnotationTrack(gr_alns, name = "Contigs", genome = "sacCer3", chromosome = "NC_001133.9")

# Add genome axis for scale
axis_track <- GenomeAxisTrack()

####### 3. Visualize the alignment ##############

#plot
plotTracks(list(axis_track,aln_track),
           from = min(start(gr_alns)),
           to = max(end(gr_alns)),
           main = 'Contig Alignments to Chromosome 1')

```
I have 2 contigs aligning to chromosome 1.

#Question 6
```{r 6}
assembly <- readDNAStringSet('/Users/mtaillefer00/Documents/BIOL_4315_LAB_3_MT/data/flye_output/assembly.fasta')

longest_contig <- assembly[which.max(width(assembly))]

writeXStringSet(longest_contig, 'longest_contig.fasta')

```

#Question 7
```{bash, eval = FALSE}
samtools view -bS cds_aln.sam > cds_aln.bam
samtools sort cds_aln.bam -o cds_aln.sorted.bam
samtools index cds_aln.sorted.bam
```

#Question 8
```{r q8, fig.width=16, fig.height=12}
#open bam file
bam_cds <- BamFile('/Users/mtaillefer00/Documents/BIOL_4315_LAB_3_MT/data/cds_aln.sorted.bam')

#read alignment
alns_cds <- readGAlignments(bam_cds)

#convert to GRanges
gr_alns_cds <- granges(alns_cds)

options(ucscChromosomeNames = FALSE)

aln_track_cds <- AnnotationTrack(gr_alns_cds, name = "Contigs", genome = "sacCer3", chromosome = "contig_144")

# Add genome axis for scale
axis_track_cds <- GenomeAxisTrack()

# Plot
plotTracks(list(axis_track_cds, aln_track_cds),
          from = min(start(gr_alns_cds)),
          to = max(end(gr_alns_cds)),
          main = "Longest Contig Alignments to the Cds")

```